name: Build and Deploy Docker Bot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/transmission-telegram-bot:latest

      - name: Deploy to Vultr Instance via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: ${{ secrets.VULTR_USER }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          port: ${{ secrets.VULTR_SSH_PORT || '22' }}
          script: |
            # Create minimal config directory for logs
            mkdir -p /root/transmission-telegram-bot/logs
            
            # Pull and run the container
            docker pull muzaparoff/transmission-telegram-bot:latest
            docker stop transmission-telegram-bot || true
            docker rm transmission-telegram-bot || true
            docker run -d --restart unless-stopped --name transmission-telegram-bot \
                      -v /root/transmission-telegram-bot/logs:/app/logs \
                      -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
                      -e TRANSMISSION_HOST=${{ secrets.TRANSMISSION_HOST }} \
                      -e TRANSMISSION_PORT=${{ secrets.TRANSMISSION_PORT }} \
                      -e TRANSMISSION_USER=${{ secrets.TRANSMISSION_USER }} \
                      -e TRANSMISSION_PASSWORD=${{ secrets.TRANSMISSION_PASSWORD }} \
                      -e DOWNLOAD_DIRS='{"Action":"/volume1/plex/Action","Classic":"/volume1/plex/Classic","Comedy":"/volume1/plex/Comedy","Comics":"/volume1/plex/Comics","Drama":"/volume1/plex/Drama","Horror":"/volume1/plex/Horror&Thriller","Kids":"/volume1/plex/Kids","TVShows":"/volume1/plex/TV-Shows","KidsShows":"/volume1/plex/Animated-TV-Shows","Romantic":"/volume1/plex/Romantic"}' \
                      muzaparoff/transmission-telegram-bot:latest
                      